import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Menu from "./components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full`}
    >
      <body className="h-full">
        <header className="flex justify-between items-center p-4 border-b border-gray-200">
          <Link href="/">Amelia Huimin Shen</Link>
          <Menu />
        </header>
        {children}
      </body>
    </html>
  );
}
