import { Lato } from "next/font/google";
import "./globals.css";
import SiteHeader from "./components/SiteHeader";
import Footer from "./components/Footer";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"], // optional but recommended
});

// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
//   weight: ["300", "400", "700"], // optional but recommended
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full ${lato.variable}`}>
      <body className={"h-full min-h-screen flex flex-col font-sans"}>
        <SiteHeader />
        {/* Grow to keep footer at the bottom */}
        <main className="grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
